version: '3.5'
services:
  #----------------------------------------------#
  # SSH Logging to influx for georeferenced results
  #----------------------------------------------#
  ssh-log-to-influx:
    image: acouvreur/ssh-log-to-influx:latest
    restart: always
    container_name: ssh-log-to-influx
    environment:
      - INFLUX_HOST=influxdb
      - INFLUX_DB=telegraf
    ports:
      - 7070:7070/tcp

  #----------------------------------------------#
  # InfluxDB : time series database
  #----------------------------------------------#
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - example_network
    ports:
      - 8086:8086
    volumes:
      - influxdb_data:/var/lib/influxdb
  #----------------------------------------------#
  # Endlessh: honeypot tar pit
  #----------------------------------------------#        
  endlessh:
    container_name: endlessh
    image: shizunge/endlessh-go:latest
    restart: always
    command:
      - -interval_ms=1000
      - -logtostderr
      - -v=1
      - -enable_prometheus
      - -geoip_supplier=ip-api
    networks:
      - example_network
    ports:
      # SSH port
      - 2222:2222
      # Prometheus metrics port
      - 127.0.0.1:2112:2112
  #--------------------------------------------------#
  # Prometheus
  #--------------------------------------------------#
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command: 
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=45d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-admin-api
    networks:
      - example_network
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
  #----------------------------------------------#
  # Grafana : analytics and monitoring
  #----------------------------------------------#
  grafana:
    image: grafana/grafana-enterprise:latest
    container_name: grafana
    restart: always
    networks:
      - example_network
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=maruf
      - GF_SECURITY_ADMIN_PASSWORD=parp0la
      - GF_INSTALL_PLUGINS=grafana-worldmap-panel,grafana-piechart-panel  
    volumes:
      - grafana_var:/var/lib/grafana/
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards

networks:
  example_network:

volumes:
  prometheus:
  grafana_var:
  grafana_data:
  influxdb_data:
